FROM node:20.8.0-alpine as buildstage

WORKDIR /app

COPY package.json /app

RUN npm install --legacy-peer-deps

COPY . /app

RUN npm run build




FROM nginx:alpine3.18

WORKDIR /usr/share/nginx/html

RUN rm -rf /usr/share/nginx/html/*
COPY nginx.conf /etc/nginx/nginx.conf
# COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=buildstage /app/build .

ENTRYPOINT ["nginx", "-g", "daemon off;"]